<?php

namespace App\DB\Migration;

/**
 * @inheritDoc
 *
 * @property \PHPFUI\ORM\RecordCursor<\App\Record\File> $FileChildren
 * @property \App\Record\Folder $parentFolder
 *
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property string $fileFolder MySQL type varchar(255)
 * @property int $fileFolderId MySQL type int
 * @property ?int $parentFolderId MySQL type int
 * @property ?int $permissionId MySQL type int
 * @property \App\Record\Permission $permission related record
 */
class FileFolder extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'fileFolder' => ['varchar(255)', 'string', 255, false, '', ],
		'fileFolderId' => ['int', 'int', 0, false, ],
		'parentFolderId' => ['int', 'int', 0, true, 0, ],
		'permissionId' => ['int', 'int', 0, true, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['folderId', ];

	protected static string $table = 'fileFolder';

	/** @var array<string, array<string>> */
	 protected static array $virtualFields = [
	 	'FileChildren' => [\PHPFUI\ORM\Children::class, \App\Table\File::class],
	 	'parentFolder' => [\PHPFUI\ORM\RelatedRecord::class, \App\Record\Folder::class],
	 ];

	 public function clean() : static
		 {
		 $this->cleanProperName('fileFolder');

		 return $this;
		 }
	}
