<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class AdditionalEmail extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'email' => ['required', 'maxlength', 'email'],
		'additionalEmailId' => ['integer'],
		'memberId' => ['required', 'integer'],
		'verified' => ['required', 'integer'],
	];
	}
