<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class AuditTrail extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'additional' => ['maxlength'],
		'auditTrailId' => ['integer'],
		'input' => ['maxlength'],
		'memberId' => ['required', 'integer'],
		'statement' => ['maxlength'],
		'time' => ['required', 'maxlength', 'datetime'],
	];
	}
