<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class Banner extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'bannerId' => ['integer'],
		'css' => ['maxlength'],
		'description' => ['maxlength'],
		'endDate' => ['required', 'date', 'gte_field:startDate'],
		'fileNameExt' => ['maxlength'],
		'html' => ['maxlength'],
		'js' => ['maxlength'],
		'pending' => ['required', 'integer'],
		'startDate' => ['required', 'date', 'lte_field:endDate'],
		'url' => ['maxlength', 'website|istarts_with:/istarts_with:#', 'required'],
	];
	}
