<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class BlogItem extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'blogId' => ['required', 'integer'],
		'ranking' => ['required', 'integer'],
		'storyId' => ['required', 'integer'],
	];
	}
