<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class Event extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'directionsUrl' => ['maxlength', 'website'],
		'endTime' => ['maxlength', 'gt_field:startTime'],
		'lastRegistrationDate' => ['required', 'date', 'lte_field:eventDate'],
		'checks' => ['required', 'integer'],
		'commentTitle' => ['required', 'maxlength'],
		'door' => ['required', 'integer'],
		'eventDate' => ['required', 'maxlength', 'date'],
		'eventId' => ['integer'],
		'location' => ['maxlength'],
		'maxDiscounts' => ['required', 'integer'],
		'newMemberDiscount' => ['required', 'number', 'lte_field:price'],
		'maxReservations' => ['required', 'integer'],
		'membersOnly' => ['required', 'integer'],
		'newMemberDate' => ['maxlength', 'date'],
		'numberReservations' => ['integer'],
		'organizer' => ['integer'],
		'paypal' => ['required', 'integer'],
		'price' => ['required', 'number'],
		'publicDate' => ['date', 'lte_field:registrationStartDate', 'lte_field:eventDate'],
		'registrationStartDate' => ['date', 'lte_field:lastRegistrationDate', 'lte_field:eventDate'],
		'startTime' => ['maxlength', 'lt_field:endTime'],
		'requireComment' => ['required', 'integer'],
		'showComments' => ['required', 'integer'],
		'showRegistered' => ['required', 'integer'],
		'title' => ['maxlength'],
	];
	}
