<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class File extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'description' => ['maxlength'],
		'extension' => ['required', 'maxlength'],
		'fileId' => ['integer'],
		'fileName' => ['required', 'maxlength'],
		'folderId' => ['required', 'integer'],
		'memberId' => ['integer'],
		'public' => ['required', 'integer'],
		'uploaded' => ['maxlength', 'datetime'],
	];
	}
