<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class Folder extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'folderId' => ['integer'],
		'name' => ['required', 'maxlength'],
		'parentFolderId' => ['integer'],
		'permissionId' => ['integer'],
	];
	}
