<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class HeaderContent extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'active' => ['required', 'integer'],
		'content' => ['maxlength'],
		'css' => ['maxlength'],
		'endDate' => ['maxlength', 'date'],
		'headerContentId' => ['integer'],
		'javaScript' => ['maxlength'],
		'name' => ['maxlength'],
		'showDay' => ['integer'],
		'showMonth' => ['integer'],
		'startDate' => ['maxlength', 'date'],
		'urlPath' => ['maxlength', 'required'],
	];
	}
