<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class InvoiceItem extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'description' => ['maxlength'],
		'detailLine' => ['maxlength'],
		'invoiceId' => ['required', 'integer'],
		'price' => ['number'],
		'quantity' => ['integer'],
		'shipping' => ['number'],
		'storeItemDetailId' => ['required', 'integer'],
		'storeItemId' => ['required', 'integer'],
		'tax' => ['number'],
		'title' => ['maxlength'],
	];
	}
