<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class Invoice extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'discount' => ['number'],
		'discountCodeId' => ['integer'],
		'errors' => ['maxlength'],
		'fullfillmentDate' => ['maxlength', 'date'],
		'instructions' => ['maxlength'],
		'invoiceId' => ['integer'],
		'memberId' => ['required', 'integer'],
		'orderDate' => ['required', 'maxlength', 'date'],
		'paidByCheck' => ['required', 'integer'],
		'paymentDate' => ['maxlength', 'date'],
		'paypalPaid' => ['number'],
		'paypaltx' => ['required', 'maxlength'],
		'pointsUsed' => ['integer'],
		'totalPrice' => ['number'],
		'totalShipping' => ['number'],
		'totalTax' => ['number'],
	];
	}
