<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class Job extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'date' => ['required', 'maxlength', 'date'],
		'description' => ['maxlength'],
		'jobEventId' => ['integer'],
		'jobId' => ['integer'],
		'location' => ['maxlength'],
		'organizer' => ['integer'],
		'title' => ['maxlength', 'required'],
	];
	}
