<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class JobEvent extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'cutoffDate' => ['date', 'lte_field:date'],
		'date' => ['required', 'date', 'gte_field:cutoffDate'],
		'jobEventId' => ['integer'],
		'name' => ['maxlength'],
		'organizer' => ['integer'],
	];
	}
