<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class MailPiece extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'email' => ['maxlength', 'email'],
		'mailItemId' => ['required', 'integer'],
		'mailPieceId' => ['integer'],
		'memberId' => ['integer'],
		'name' => ['maxlength'],
	];
	}
