<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class MailItem extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'body' => ['maxlength'],
		'domain' => ['maxlength'],
		'fromEmail' => ['maxlength', 'email'],
		'fromName' => ['maxlength'],
		'html' => ['integer'],
		'mailItemId' => ['integer'],
		'memberId' => ['integer'],
		'paused' => ['integer'],
		'replyTo' => ['maxlength', 'email'],
		'replyToName' => ['maxlength'],
		'title' => ['maxlength'],
	];
	}
