<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class MailAttachment extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'mailAttachmentId' => ['integer'],
		'mailItemId' => ['required', 'integer'],
		'prettyName' => ['maxlength'],
	];
	}
