<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class MemberNotice extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'body' => ['maxlength', 'required'],
		'dayOffsets' => ['required'],
		'field' => ['required', 'maxlength'],
		'memberId' => ['integer'],
		'title' => ['required', 'maxlength'],
	];
	}
