<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class Payment extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'amount' => ['number'],
		'dateReceived' => ['required', 'maxlength', 'date'],
		'enteringMemberNumber' => ['integer'],
		'invoiceId' => ['integer'],
		'membershipId' => ['integer'],
		'paymentDated' => ['maxlength', 'date'],
		'paymentId' => ['integer'],
		'paymentNumber' => ['maxlength'],
		'paymentType' => ['integer'],
	];
	}
