<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class PermissionGroup extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'groupId' => ['required', 'integer'],
		'permissionId' => ['required', 'integer'],
		'revoked' => ['required', 'integer'],
	];
	}
