<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class PhotoTag extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'frontToBack' => ['required', 'integer'],
		'leftToRight' => ['required', 'integer'],
		'memberId' => ['integer'],
		'photoId' => ['required', 'integer'],
		'photoTag' => ['required', 'maxlength'],
		'photoTagId' => ['integer'],
		'taggerId' => ['required', 'integer'],
	];
	}
