<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class PointHistory extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'editorId' => ['integer'],
		'memberId' => ['required', 'integer'],
		'oldLeaderPoints' => ['integer'],
		'time' => ['required', 'maxlength', 'datetime'],
		'volunteerPoints' => ['required', 'integer'],
	];
	}
