<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class PollAnswer extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'answer' => ['maxlength'],
		'pollAnswerId' => ['required', 'integer'],
		'pollId' => ['required', 'integer'],
	];
	}
