<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class PublicPage extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'banner' => ['integer'],
		'blog' => ['integer'],
		'blogAfter' => ['maxlength'],
		'footerMenu' => ['required', 'integer'],
		'header' => ['integer'],
		'homePageNotification' => ['required', 'integer'],
		'method' => ['maxlength'],
		'name' => ['maxlength'],
		'publicMenu' => ['required', 'integer'],
		'publicPageId' => ['integer'],
		'sequence' => ['integer'],
		'url' => ['maxlength', 'starts_with:/', 'unique'],
	];
	}
