<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class Reservation extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'address' => ['maxlength'],
		'eventId' => ['integer'],
		'invoiceId' => ['integer'],
		'memberId' => ['required', 'integer'],
		'paymentId' => ['integer'],
		'phone' => ['maxlength'],
		'pricePaid' => ['required', 'number'],
		'reservationFirstName' => ['maxlength'],
		'reservationLastName' => ['maxlength'],
		'reservationemail' => ['maxlength', 'email'],
		'signedUpAt' => ['required', 'maxlength', 'datetime'],
		'state' => ['maxlength'],
		'town' => ['maxlength'],
		'zip' => ['maxlength'],
	];
	}
