<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class SlideShow extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'active' => ['required', 'integer'],
		'endDate' => ['date', 'gte_field:startDate'],
		'added' => ['required', 'maxlength', 'datetime'],
		'alignment' => ['required', 'maxlength'],
		'memberId' => ['integer', 'minvalue:0'],
		'startDate' => ['date', 'lte_field:endDate'],
		'name' => ['maxlength'],
		'settings' => ['maxlength'],
		'slideShowId' => ['integer'],
		'updated' => ['maxlength', 'datetime'],
		'width' => ['required', 'integer'],
	];
	}
