<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class Slide extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'added' => ['required', 'maxlength', 'datetime'],
		'caption' => ['maxlength'],
		'extension' => ['maxlength'],
		'memberId' => ['integer', 'minvalue:0'],
		'photoId' => ['integer'],
		'sequence' => ['required', 'integer'],
		'showCaption' => ['required', 'integer'],
		'slideId' => ['integer'],
		'slideShowId' => ['required', 'integer'],
		'url' => ['maxlength', 'website|istarts_with:/'],
		'updated' => ['maxlength', 'datetime'],
	];
	}
