<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class Story extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'author' => ['maxlength'],
		'body' => ['maxlength'],
		'endDate' => ['date', 'gte_field:startDate'],
		'date' => ['maxlength', 'date'],
		'editorId' => ['integer'],
		'headline' => ['maxlength'],
		'javaScript' => ['maxlength'],
		'lastEdited' => ['maxlength', 'date'],
		'membersOnly' => ['integer'],
		'noTitle' => ['integer'],
		'onTop' => ['integer'],
		'showFull' => ['integer'],
		'startDate' => ['date', 'gte_field:date', 'lte_field:endDate'],
		'storyId' => ['integer'],
		'subhead' => ['maxlength'],
	];
	}
