<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class SystemEmail extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'email' => ['maxlength'],
		'mailbox' => ['maxlength'],
		'name' => ['maxlength'],
		'systemEmailId' => ['integer'],
	];
	}
