<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class Video extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'description' => ['required', 'maxlength'],
		'editor' => ['required', 'integer'],
		'fileName' => ['required', 'maxlength'],
		'hits' => ['required', 'integer'],
		'folderId' => ['integer'],
		'lastEdited' => ['required', 'maxlength', 'datetime'],
		'memberId' => ['integer'],
		'public' => ['required', 'integer'],
		'title' => ['required', 'maxlength'],
		'videoDate' => ['required', 'maxlength', 'date'],
		'videoId' => ['integer'],
	];
	}
