<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class VolunteerPoint extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'date' => ['required', 'maxlength', 'date'],
		'jobEventId' => ['required', 'integer'],
		'memberId' => ['required', 'integer'],
		'pointsAwarded' => ['required', 'integer'],
	];
	}
