<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class VolunteerPoll extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'jobEventId' => ['required', 'integer'],
		'question' => ['maxlength'],
		'volunteerPollId' => ['integer'],
	];
	}
