<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class Ziptax extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'zip_code' => ['maxlength', 'required'],
		'zip_tax_rate' => ['number', 'required'],
		'zip_id' => ['required', 'integer'],
		'zipcounty' => ['maxlength'],
		'zipstate' => ['maxlength'],
	];
	}
