<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property int $additionalEmailId MySQL type int
 * @property \App\Record\AdditionalEmail $additionalEmail related record
 * @property string $email MySQL type varchar(100)
 * @property int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property int $verified MySQL type int
 */
abstract class AdditionalEmail extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'additionalEmailId' => ['int', 'int', 0, false, ],
		'email' => ['varchar(100)', 'string', 100, false, ],
		'memberId' => ['int', 'int', 0, false, ],
		'verified' => ['int', 'int', 0, false, 0, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['additionalEmailId', ];

	protected static string $table = 'additionalEmail';
	}
