<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $additional MySQL type text
 * @property int $auditTrailId MySQL type int
 * @property \App\Record\AuditTrail $auditTrail related record
 * @property ?string $input MySQL type text
 * @property int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property ?string $statement MySQL type text
 * @property string $time MySQL type datetime
 */
abstract class AuditTrail extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'additional' => ['text', 'string', 65535, true, ],
		'auditTrailId' => ['int', 'int', 0, false, ],
		'input' => ['text', 'string', 65535, true, ],
		'memberId' => ['int', 'int', 0, false, ],
		'statement' => ['text', 'string', 65535, true, ],
		'time' => ['datetime', 'string', 20, false, null, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['auditTrailId', ];

	protected static string $table = 'auditTrail';
	}
