<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property int $bannerId MySQL type int
 * @property \App\Record\Banner $banner related record
 * @property ?string $css MySQL type text
 * @property ?string $description MySQL type varchar(200)
 * @property ?string $endDate MySQL type date
 * @property ?string $fileNameExt MySQL type char(10)
 * @property ?string $html MySQL type text
 * @property ?string $js MySQL type text
 * @property int $pending MySQL type int
 * @property ?string $startDate MySQL type date
 * @property ?string $url MySQL type varchar(200)
 */
abstract class Banner extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'bannerId' => ['int', 'int', 0, false, ],
		'css' => ['text', 'string', 65535, true, ],
		'description' => ['varchar(200)', 'string', 200, true, ],
		'endDate' => ['date', 'string', 10, true, ],
		'fileNameExt' => ['char(10)', 'string', 10, true, ],
		'html' => ['text', 'string', 65535, true, ],
		'js' => ['text', 'string', 65535, true, ],
		'pending' => ['int', 'int', 0, false, 1, ],
		'startDate' => ['date', 'string', 10, true, ],
		'url' => ['varchar(200)', 'string', 200, true, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['bannerId', ];

	protected static string $table = 'banner';
	}
