<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property int $blogId MySQL type int
 * @property \App\Record\Blog $blog related record
 * @property int $count MySQL type int
 * @property string $name MySQL type varchar(255)
 */
abstract class Blog extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'blogId' => ['int', 'int', 0, false, ],
		'count' => ['int', 'int', 0, false, 0, ],
		'name' => ['varchar(255)', 'string', 255, false, '', ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['blogId', ];

	protected static string $table = 'blog';
	}
