<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property int $blogId MySQL type int
 * @property \App\Record\Blog $blog related record
 * @property ?int $ranking MySQL type int
 * @property int $storyId MySQL type int
 * @property \App\Record\Story $story related record
 */
abstract class BlogItem extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'blogId' => ['int', 'int', 0, false, ],
		'ranking' => ['int', 'int', 0, true, 0, ],
		'storyId' => ['int', 'int', 0, false, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['blogId', 'storyId', ];

	protected static string $table = 'blogItem';
	}
