<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property int $active MySQL type int
 * @property ?string $content MySQL type mediumtext
 * @property ?string $css MySQL type mediumtext
 * @property ?string $endDate MySQL type date
 * @property int $headerContentId MySQL type int
 * @property \App\Record\HeaderContent $headerContent related record
 * @property ?string $javaScript MySQL type text
 * @property ?string $name MySQL type varchar(100)
 * @property ?int $showDay MySQL type int
 * @property ?int $showMonth MySQL type int
 * @property ?string $startDate MySQL type date
 * @property ?string $urlPath MySQL type varchar(255)
 */
abstract class HeaderContent extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'active' => ['int', 'int', 0, false, 0, ],
		'content' => ['mediumtext', 'string', 16777215, true, ],
		'css' => ['mediumtext', 'string', 16777215, true, ],
		'endDate' => ['date', 'string', 10, true, ],
		'headerContentId' => ['int', 'int', 0, false, ],
		'javaScript' => ['text', 'string', 65535, true, ],
		'name' => ['varchar(100)', 'string', 100, true, ],
		'showDay' => ['int', 'int', 0, true, ],
		'showMonth' => ['int', 'int', 0, true, ],
		'startDate' => ['date', 'string', 10, true, ],
		'urlPath' => ['varchar(255)', 'string', 255, true, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['headerContentId', ];

	protected static string $table = 'headerContent';
	}
