<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $REQUEST_METHOD MySQL type varchar(10)
 * @property ?string $REQUEST_URI MySQL type varchar(255)
 * @property ?string $_get MySQL type text
 * @property ?string $_post MySQL type text
 * @property int $httpRequestId MySQL type int
 * @property \App\Record\HttpRequest $httpRequest related record
 */
abstract class HttpRequest extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'REQUEST_METHOD' => ['varchar(10)', 'string', 10, true, ],
		'REQUEST_URI' => ['varchar(255)', 'string', 255, true, ],
		'_get' => ['text', 'string', 65535, true, ],
		'_post' => ['text', 'string', 65535, true, ],
		'httpRequestId' => ['int', 'int', 0, false, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['httpRequestId', ];

	protected static string $table = 'httpRequest';
	}
