<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?float $discount MySQL type float(10,2)
 * @property ?int $discountCodeId MySQL type int
 * @property \App\Record\DiscountCode $discountCode related record
 * @property ?string $errors MySQL type text
 * @property ?string $fullfillmentDate MySQL type date
 * @property ?string $instructions MySQL type char(125)
 * @property int $invoiceId MySQL type int
 * @property \App\Record\Invoice $invoice related record
 * @property int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property string $orderDate MySQL type date
 * @property int $paidByCheck MySQL type int
 * @property ?string $paymentDate MySQL type date
 * @property ?float $paypalPaid MySQL type decimal(7,2)
 * @property string $paypaltx MySQL type varchar(50)
 * @property ?int $pointsUsed MySQL type int
 * @property ?float $totalPrice MySQL type decimal(7,2)
 * @property ?float $totalShipping MySQL type decimal(7,2)
 * @property ?float $totalTax MySQL type decimal(7,2)
 */
abstract class Invoice extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'discount' => ['float(10,2)', 'float', 10, true, ],
		'discountCodeId' => ['int', 'int', 0, true, ],
		'errors' => ['text', 'string', 65535, true, ],
		'fullfillmentDate' => ['date', 'string', 10, true, ],
		'instructions' => ['char(125)', 'string', 125, true, ],
		'invoiceId' => ['int', 'int', 0, false, ],
		'memberId' => ['int', 'int', 0, false, ],
		'orderDate' => ['date', 'string', 10, false, ],
		'paidByCheck' => ['int', 'int', 0, false, 0, ],
		'paymentDate' => ['date', 'string', 10, true, ],
		'paypalPaid' => ['decimal(7,2)', 'float', 7, true, ],
		'paypaltx' => ['varchar(50)', 'string', 50, false, '', ],
		'pointsUsed' => ['int', 'int', 0, true, ],
		'totalPrice' => ['decimal(7,2)', 'float', 7, true, ],
		'totalShipping' => ['decimal(7,2)', 'float', 7, true, ],
		'totalTax' => ['decimal(7,2)', 'float', 7, true, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['invoiceId', ];

	protected static string $table = 'invoice';
	}
