<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property string $date MySQL type date
 * @property ?string $description MySQL type text
 * @property ?int $jobEventId MySQL type int
 * @property \App\Record\JobEvent $jobEvent related record
 * @property int $jobId MySQL type int
 * @property \App\Record\Job $job related record
 * @property ?string $location MySQL type char(100)
 * @property ?int $organizer MySQL type int
 * @property ?string $title MySQL type char(100)
 */
abstract class Job extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'date' => ['date', 'string', 10, false, ],
		'description' => ['text', 'string', 65535, true, ],
		'jobEventId' => ['int', 'int', 0, true, ],
		'jobId' => ['int', 'int', 0, false, ],
		'location' => ['char(100)', 'string', 100, true, ],
		'organizer' => ['int', 'int', 0, true, ],
		'title' => ['char(100)', 'string', 100, true, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['jobId', ];

	protected static string $table = 'job';
	}
