<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $cutoffDate MySQL type date
 * @property string $date MySQL type date
 * @property int $jobEventId MySQL type int
 * @property \App\Record\JobEvent $jobEvent related record
 * @property ?string $name MySQL type char(100)
 * @property ?int $organizer MySQL type int
 */
abstract class JobEvent extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'cutoffDate' => ['date', 'string', 10, true, ],
		'date' => ['date', 'string', 10, false, ],
		'jobEventId' => ['int', 'int', 0, false, ],
		'name' => ['char(100)', 'string', 100, true, ],
		'organizer' => ['int', 'int', 0, true, 0, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['jobEventId', ];

	protected static string $table = 'jobEvent';
	}
