<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $body MySQL type mediumtext
 * @property ?string $domain MySQL type varchar(30)
 * @property ?string $fromEmail MySQL type varchar(255)
 * @property ?string $fromName MySQL type varchar(255)
 * @property ?int $html MySQL type int
 * @property int $mailItemId MySQL type int
 * @property \App\Record\MailItem $mailItem related record
 * @property ?int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property ?int $paused MySQL type int
 * @property ?string $replyTo MySQL type varchar(100)
 * @property ?string $replyToName MySQL type varchar(100)
 * @property ?string $title MySQL type varchar(255)
 */
abstract class MailItem extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'body' => ['mediumtext', 'string', 16777215, true, ],
		'domain' => ['varchar(30)', 'string', 30, true, '', ],
		'fromEmail' => ['varchar(255)', 'string', 255, true, '', ],
		'fromName' => ['varchar(255)', 'string', 255, true, '', ],
		'html' => ['int', 'int', 0, true, 0, ],
		'mailItemId' => ['int', 'int', 0, false, ],
		'memberId' => ['int', 'int', 0, true, ],
		'paused' => ['int', 'int', 0, true, 0, ],
		'replyTo' => ['varchar(100)', 'string', 100, true, '', ],
		'replyToName' => ['varchar(100)', 'string', 100, true, '', ],
		'title' => ['varchar(255)', 'string', 255, true, '', ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['mailItemId', ];

	protected static string $table = 'mailItem';
	}
