<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $body MySQL type mediumtext
 * @property string $dayOffsets MySQL type varchar(255)
 * @property string $field MySQL type varchar(30)
 * @property ?int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property int $memberNoticeId MySQL type int
 * @property \App\Record\MemberNotice $memberNotice related record
 * @property ?int $overridePreferences MySQL type int
 * @property int $summary MySQL type int
 * @property string $title MySQL type varchar(255)
 */
abstract class MemberNotice extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'body' => ['mediumtext', 'string', 16777215, true, ],
		'dayOffsets' => ['varchar(255)', 'string', 255, false, ],
		'field' => ['varchar(30)', 'string', 30, false, ],
		'memberId' => ['int', 'int', 0, true, ],
		'memberNoticeId' => ['int', 'int', 0, false, ],
		'overridePreferences' => ['int', 'int', 0, true, 0, ],
		'summary' => ['int', 'int', 0, false, 1, ],
		'title' => ['varchar(255)', 'string', 255, false, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['memberNoticeId', ];

	protected static string $table = 'memberNotice';
	}
