<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property int $migrationId MySQL type int
 * @property \App\Record\Migration $migration related record
 * @property string $ran MySQL type datetime
 */
abstract class Migration extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'migrationId' => ['int', 'int', 0, false, ],
		'ran' => ['datetime', 'string', 20, false, null, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['migrationId', ];

	protected static string $table = 'migration';
	}
