<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $lastLogin MySQL type datetime
 * @property int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property int $oauthUserId MySQL type int
 * @property \App\Record\OauthUser $oauthUser related record
 * @property ?string $password MySQL type varchar(255)
 * @property ?string $permissions MySQL type text
 * @property ?string $userName MySQL type varchar(100)
 */
abstract class OauthUser extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'lastLogin' => ['datetime', 'string', 20, true, ],
		'memberId' => ['int', 'int', 0, false, ],
		'oauthUserId' => ['int', 'int', 0, false, ],
		'password' => ['varchar(255)', 'string', 255, true, ],
		'permissions' => ['text', 'string', 65535, true, ],
		'userName' => ['varchar(100)', 'string', 100, true, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['oauthUserId', ];

	protected static string $table = 'oauthUser';
	}
