<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $client MySQL type varchar(255)
 * @property string $expires MySQL type datetime
 * @property int $oauthTokenId MySQL type int
 * @property \App\Record\OauthToken $oauthToken related record
 * @property ?int $oauthUserId MySQL type int
 * @property \App\Record\OauthUser $oauthUser related record
 * @property ?string $scopes MySQL type text
 * @property ?string $token MySQL type varchar(255)
 */
abstract class OauthToken extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'client' => ['varchar(255)', 'string', 255, true, ],
		'expires' => ['datetime', 'string', 20, false, null, ],
		'oauthTokenId' => ['int', 'int', 0, false, ],
		'oauthUserId' => ['int', 'int', 0, true, ],
		'scopes' => ['text', 'string', 65535, true, ],
		'token' => ['varchar(255)', 'string', 255, true, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['oauthTokenId', ];

	protected static string $table = 'oauthToken';
	}
