<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?float $amount MySQL type decimal(7,2)
 * @property string $createdDate MySQL type date
 * @property ?int $createdMemberNumber MySQL type int
 * @property ?int $invoiceId MySQL type int
 * @property \App\Record\Invoice $invoice related record
 * @property int $paypalRefundId MySQL type int
 * @property \App\Record\PaypalRefund $paypalRefund related record
 * @property ?string $paypaltx MySQL type varchar(20)
 * @property ?string $refundOnDate MySQL type date
 * @property ?string $refundedDate MySQL type date
 * @property ?string $response MySQL type text
 */
abstract class PaypalRefund extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'amount' => ['decimal(7,2)', 'float', 7, true, ],
		'createdDate' => ['date', 'string', 10, false, ],
		'createdMemberNumber' => ['int', 'int', 0, true, ],
		'invoiceId' => ['int', 'int', 0, true, ],
		'paypalRefundId' => ['int', 'int', 0, false, ],
		'paypaltx' => ['varchar(20)', 'string', 20, true, ],
		'refundOnDate' => ['date', 'string', 10, true, ],
		'refundedDate' => ['date', 'string', 10, true, ],
		'response' => ['text', 'string', 65535, true, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['paypalRefundId', ];

	protected static string $table = 'paypalRefund';
	}
