<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property int $groupId MySQL type int
 * @property int $permissionId MySQL type int
 * @property \App\Record\Permission $permission related record
 * @property int $revoked MySQL type int
 */
abstract class PermissionGroup extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'groupId' => ['int', 'int', 0, false, ],
		'permissionId' => ['int', 'int', 0, false, ],
		'revoked' => ['int', 'int', 0, false, 0, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['groupId', 'permissionId', ];

	protected static string $table = 'permissionGroup';
	}
