<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $menu MySQL type varchar(255)
 * @property ?string $name MySQL type varchar(255)
 * @property int $permissionId MySQL type int
 * @property \App\Record\Permission $permission related record
 * @property int $system MySQL type tinyint
 */
abstract class Permission extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'menu' => ['varchar(255)', 'string', 255, true, ],
		'name' => ['varchar(255)', 'string', 255, true, ],
		'permissionId' => ['int', 'int', 0, false, ],
		'system' => ['tinyint', 'int', 0, false, 0, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['permissionId', ];

	protected static string $table = 'permission';
	}
