<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property int $frontToBack MySQL type int
 * @property int $leftToRight MySQL type int
 * @property ?int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property int $photoId MySQL type int
 * @property \App\Record\Photo $photo related record
 * @property string $photoTag MySQL type varchar(100)
 * @property int $photoTagId MySQL type int
 * @property int $taggerId MySQL type int
 */
abstract class PhotoTag extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'frontToBack' => ['int', 'int', 0, false, ],
		'leftToRight' => ['int', 'int', 0, false, ],
		'memberId' => ['int', 'int', 0, true, ],
		'photoId' => ['int', 'int', 0, false, ],
		'photoTag' => ['varchar(100)', 'string', 100, false, '', ],
		'photoTagId' => ['int', 'int', 0, false, ],
		'taggerId' => ['int', 'int', 0, false, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['photoTagId', ];

	protected static string $table = 'photoTag';
	}
