<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $description MySQL type varchar(255)
 * @property string $extension MySQL type varchar(10)
 * @property int $folderId MySQL type int
 * @property \App\Record\Folder $folder related record
 * @property ?int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property int $photoId MySQL type int
 * @property \App\Record\Photo $photo related record
 * @property int $public MySQL type int
 * @property ?string $taken MySQL type datetime
 * @property int $thumbnail MySQL type int
 * @property string $uploaded MySQL type datetime
 */
abstract class Photo extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'description' => ['varchar(255)', 'string', 255, true, ],
		'extension' => ['varchar(10)', 'string', 10, false, '', ],
		'folderId' => ['int', 'int', 0, false, ],
		'memberId' => ['int', 'int', 0, true, ],
		'photoId' => ['int', 'int', 0, false, ],
		'public' => ['int', 'int', 0, false, 0, ],
		'taken' => ['datetime', 'string', 20, true, ],
		'thumbnail' => ['int', 'int', 0, false, 0, ],
		'uploaded' => ['datetime', 'string', 20, false, null, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['photoId', ];

	protected static string $table = 'photo';
	}
