<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property string $photoComment MySQL type varchar(255)
 * @property int $photoCommentId MySQL type int
 * @property int $photoId MySQL type int
 * @property \App\Record\Photo $photo related record
 * @property string $timestamp MySQL type datetime
 */
abstract class PhotoComment extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'memberId' => ['int', 'int', 0, false, ],
		'photoComment' => ['varchar(255)', 'string', 255, false, '', ],
		'photoCommentId' => ['int', 'int', 0, false, ],
		'photoId' => ['int', 'int', 0, false, ],
		'timestamp' => ['datetime', 'string', 20, false, null, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['photoCommentId', ];

	protected static string $table = 'photoComment';
	}
