<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?int $emailConfirmation MySQL type int
 * @property string $endDate MySQL type date
 * @property ?int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property ?int $membershipOnly MySQL type int
 * @property int $pollId MySQL type int
 * @property \App\Record\Poll $poll related record
 * @property ?string $question MySQL type text
 * @property ?int $required MySQL type int
 * @property string $startDate MySQL type date
 * @property ?int $storyId MySQL type int
 * @property \App\Record\Story $story related record
 */
abstract class Poll extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'emailConfirmation' => ['int', 'int', 0, true, ],
		'endDate' => ['date', 'string', 10, false, ],
		'memberId' => ['int', 'int', 0, true, ],
		'membershipOnly' => ['int', 'int', 0, true, ],
		'pollId' => ['int', 'int', 0, false, ],
		'question' => ['text', 'string', 65535, true, ],
		'required' => ['int', 'int', 0, true, ],
		'startDate' => ['date', 'string', 10, false, ],
		'storyId' => ['int', 'int', 0, true, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['pollId', ];

	protected static string $table = 'poll';
	}
