<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $answer MySQL type varchar(250)
 * @property int $pollAnswerId MySQL type int
 * @property \App\Record\PollAnswer $pollAnswer related record
 * @property int $pollId MySQL type int
 * @property \App\Record\Poll $poll related record
 */
abstract class PollAnswer extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'answer' => ['varchar(250)', 'string', 250, true, ],
		'pollAnswerId' => ['int', 'int', 0, false, ],
		'pollId' => ['int', 'int', 0, false, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['pollId', 'pollAnswerId', ];

	protected static string $table = 'pollAnswer';
	}
