<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?int $answer MySQL type int
 * @property int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property int $membershipId MySQL type int
 * @property \App\Record\Membership $membership related record
 * @property int $pollId MySQL type int
 * @property \App\Record\Poll $poll related record
 */
abstract class PollResponse extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'answer' => ['int', 'int', 0, true, ],
		'memberId' => ['int', 'int', 0, false, ],
		'membershipId' => ['int', 'int', 0, false, ],
		'pollId' => ['int', 'int', 0, false, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['pollId', 'membershipId', 'memberId', ];

	protected static string $table = 'pollResponse';
	}
