<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?int $banner MySQL type tinyint(1)
 * @property ?int $blog MySQL type tinyint(1)
 * @property ?string $blogAfter MySQL type varchar(100)
 * @property int $footerMenu MySQL type tinyint
 * @property ?int $header MySQL type tinyint(1)
 * @property int $hidden MySQL type int
 * @property int $homePageNotification MySQL type tinyint
 * @property ?string $method MySQL type varchar(200)
 * @property ?string $name MySQL type varchar(200)
 * @property int $publicMenu MySQL type tinyint
 * @property int $publicPageId MySQL type int
 * @property \App\Record\PublicPage $publicPage related record
 * @property ?int $sequence MySQL type int
 * @property ?string $url MySQL type varchar(100)
 */
abstract class PublicPage extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'banner' => ['tinyint(1)', 'int', 1, true, 0, ],
		'blog' => ['tinyint(1)', 'int', 1, true, 0, ],
		'blogAfter' => ['varchar(100)', 'string', 100, true, ],
		'footerMenu' => ['tinyint', 'int', 0, false, 0, ],
		'header' => ['tinyint(1)', 'int', 1, true, 0, ],
		'hidden' => ['int', 'int', 0, false, 0, ],
		'homePageNotification' => ['tinyint', 'int', 0, false, 0, ],
		'method' => ['varchar(200)', 'string', 200, true, ],
		'name' => ['varchar(200)', 'string', 200, true, ],
		'publicMenu' => ['tinyint', 'int', 0, false, 1, ],
		'publicPageId' => ['int', 'int', 0, false, ],
		'sequence' => ['int', 'int', 0, true, 0, ],
		'url' => ['varchar(100)', 'string', 100, true, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['publicPageId', ];

	protected static string $table = 'publicPage';
	}
