<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property string $originalUrl MySQL type varchar(255)
 * @property int $redirectId MySQL type int
 * @property \App\Record\Redirect $redirect related record
 * @property string $redirectUrl MySQL type varchar(255)
 */
abstract class Redirect extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'originalUrl' => ['varchar(255)', 'string', 255, false, ],
		'redirectId' => ['int', 'int', 0, false, ],
		'redirectUrl' => ['varchar(255)', 'string', 255, false, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['redirectId', ];

	protected static string $table = 'redirect';
	}
