<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property string $comments MySQL type varchar(255)
 * @property ?string $email MySQL type varchar(50)
 * @property ?int $eventId MySQL type int
 * @property \App\Record\Event $event related record
 * @property ?string $firstName MySQL type varchar(50)
 * @property ?string $lastName MySQL type varchar(50)
 * @property ?int $reservationId MySQL type int
 * @property \App\Record\Reservation $reservation related record
 * @property int $reservationPersonId MySQL type int
 * @property \App\Record\ReservationPerson $reservationPerson related record
 */
abstract class ReservationPerson extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'comments' => ['varchar(255)', 'string', 255, false, '', ],
		'email' => ['varchar(50)', 'string', 50, true, ],
		'eventId' => ['int', 'int', 0, true, ],
		'firstName' => ['varchar(50)', 'string', 50, true, ],
		'lastName' => ['varchar(50)', 'string', 50, true, ],
		'reservationId' => ['int', 'int', 0, true, ],
		'reservationPersonId' => ['int', 'int', 0, false, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['reservationPersonId', ];

	protected static string $table = 'reservationPerson';
	}
