<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property string $name MySQL type varchar(30)
 * @property ?string $value MySQL type text
 */
abstract class Setting extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'name' => ['varchar(30)', 'string', 30, false, '', ],
		'value' => ['text', 'string', 65535, true, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['name', ];

	protected static string $table = 'setting';
	}
