<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property int $active MySQL type int
 * @property string $added MySQL type datetime
 * @property string $alignment MySQL type varchar(20)
 * @property ?string $endDate MySQL type date
 * @property ?int $memberId MySQL type int unsigned
 * @property \App\Record\Member $member related record
 * @property ?string $name MySQL type varchar(255)
 * @property ?string $settings MySQL type text
 * @property int $slideShowId MySQL type int
 * @property \App\Record\SlideShow $slideShow related record
 * @property ?string $startDate MySQL type date
 * @property ?string $updated MySQL type datetime
 * @property int $width MySQL type int
 */
abstract class SlideShow extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'active' => ['int', 'int', 0, false, 0, ],
		'added' => ['datetime', 'string', 20, false, null, ],
		'alignment' => ['varchar(20)', 'string', 20, false, '', ],
		'endDate' => ['date', 'string', 10, true, ],
		'memberId' => ['int unsigned', 'int', 0, true, ],
		'name' => ['varchar(255)', 'string', 255, true, ],
		'settings' => ['text', 'string', 65535, true, ],
		'slideShowId' => ['int', 'int', 0, false, ],
		'startDate' => ['date', 'string', 10, true, ],
		'updated' => ['datetime', 'string', 20, true, ],
		'width' => ['int', 'int', 0, false, 0, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['slideShowId', ];

	protected static string $table = 'slideShow';
	}
