<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $author MySQL type varchar(30)
 * @property ?string $body MySQL type mediumtext
 * @property ?string $date MySQL type date
 * @property ?int $editorId MySQL type int
 * @property ?string $endDate MySQL type date
 * @property ?string $headline MySQL type varchar(200)
 * @property ?string $javaScript MySQL type text
 * @property ?string $lastEdited MySQL type date
 * @property ?int $membersOnly MySQL type int
 * @property ?int $noTitle MySQL type int
 * @property ?int $onTop MySQL type int
 * @property ?int $showFull MySQL type int
 * @property ?string $startDate MySQL type date
 * @property int $storyId MySQL type int
 * @property \App\Record\Story $story related record
 * @property ?string $subhead MySQL type varchar(200)
 */
abstract class Story extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'author' => ['varchar(30)', 'string', 30, true, ],
		'body' => ['mediumtext', 'string', 16777215, true, ],
		'date' => ['date', 'string', 10, true, ],
		'editorId' => ['int', 'int', 0, true, ],
		'endDate' => ['date', 'string', 10, true, ],
		'headline' => ['varchar(200)', 'string', 200, true, ],
		'javaScript' => ['text', 'string', 65535, true, ],
		'lastEdited' => ['date', 'string', 10, true, ],
		'membersOnly' => ['int', 'int', 0, true, 0, ],
		'noTitle' => ['int', 'int', 0, true, ],
		'onTop' => ['int', 'int', 0, true, ],
		'showFull' => ['int', 'int', 0, true, ],
		'startDate' => ['date', 'string', 10, true, ],
		'storyId' => ['int', 'int', 0, false, ],
		'subhead' => ['varchar(200)', 'string', 200, true, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['storyId', ];

	protected static string $table = 'story';
	}
