<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $email MySQL type varchar(100)
 * @property ?string $mailbox MySQL type varchar(50)
 * @property ?string $name MySQL type varchar(50)
 * @property int $systemEmailId MySQL type int
 * @property \App\Record\SystemEmail $systemEmail related record
 */
abstract class SystemEmail extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'email' => ['varchar(100)', 'string', 100, true, ],
		'mailbox' => ['varchar(50)', 'string', 50, true, ],
		'name' => ['varchar(50)', 'string', 50, true, ],
		'systemEmailId' => ['int', 'int', 0, false, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['systemEmailId', ];

	protected static string $table = 'systemEmail';
	}
