<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property int $permissionGroup MySQL type int
 * @property int $revoked MySQL type int
 */
abstract class UserPermission extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'memberId' => ['int', 'int', 0, false, ],
		'permissionGroup' => ['int', 'int', 0, false, ],
		'revoked' => ['int', 'int', 0, false, 0, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['memberId', 'permissionGroup', ];

	protected static string $table = 'userPermission';
	}
