<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property int $jobEventId MySQL type int
 * @property \App\Record\JobEvent $jobEvent related record
 * @property ?string $question MySQL type text
 * @property int $volunteerPollId MySQL type int
 * @property \App\Record\VolunteerPoll $volunteerPoll related record
 */
abstract class VolunteerPoll extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'jobEventId' => ['int', 'int', 0, false, ],
		'question' => ['text', 'string', 65535, true, ],
		'volunteerPollId' => ['int', 'int', 0, false, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['volunteerPollId', ];

	protected static string $table = 'volunteerPoll';
	}
