<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $email MySQL type text
 * @property ?int $jobId MySQL type int
 * @property \App\Record\Job $job related record
 * @property ?int $jobShiftId MySQL type int
 * @property \App\Record\JobShift $jobShift related record
 * @property int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property string $notes MySQL type varchar(255)
 * @property ?int $shiftLeader MySQL type int
 * @property string $signedUpDate MySQL type datetime
 * @property int $volunteerJobShiftId MySQL type int
 * @property \App\Record\VolunteerJobShift $volunteerJobShift related record
 * @property int $worked MySQL type tinyint
 */
abstract class VolunteerJobShift extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'email' => ['text', 'string', 65535, true, ],
		'jobId' => ['int', 'int', 0, true, ],
		'jobShiftId' => ['int', 'int', 0, true, ],
		'memberId' => ['int', 'int', 0, false, ],
		'notes' => ['varchar(255)', 'string', 255, false, '', ],
		'shiftLeader' => ['int', 'int', 0, true, ],
		'signedUpDate' => ['datetime', 'string', 20, false, null, ],
		'volunteerJobShiftId' => ['int', 'int', 0, false, ],
		'worked' => ['tinyint', 'int', 0, false, 0, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['volunteerJobShiftId', ];

	protected static string $table = 'volunteerJobShift';
	}
