<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property string $date MySQL type date
 * @property int $jobEventId MySQL type int
 * @property \App\Record\JobEvent $jobEvent related record
 * @property int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property int $pointsAwarded MySQL type int
 */
abstract class VolunteerPoint extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'date' => ['date', 'string', 10, false, ],
		'jobEventId' => ['int', 'int', 0, false, ],
		'memberId' => ['int', 'int', 0, false, ],
		'pointsAwarded' => ['int', 'int', 0, false, 0, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['jobEventId', 'date', 'memberId', ];

	protected static string $table = 'volunteerPoint';
	}
