<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $zip_code MySQL type varchar(32)
 * @property int $zip_id MySQL type int
 * @property ?float $zip_tax_rate MySQL type decimal(7,4)
 * @property ?string $zipcounty MySQL type varchar(32)
 * @property ?string $zipstate MySQL type varchar(32)
 */
abstract class Ziptax extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'zip_code' => ['varchar(32)', 'string', 32, true, ],
		'zip_id' => ['int', 'int', 0, false, ],
		'zip_tax_rate' => ['decimal(7,4)', 'float', 7, true, ],
		'zipcounty' => ['varchar(32)', 'string', 32, true, ],
		'zipstate' => ['varchar(32)', 'string', 32, true, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['zip_id', ];

	protected static string $table = 'ziptax';
	}
